#!/usr/bin/env php
<?php

require __DIR__.'/../../autoload.php';
//require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Custom Laravel Utilities', '1.0');
$app->add(new Mmanos\Installer\Console\NewCommand);
$app->add(new Mmanos\Installer\Console\PrepareCommand);
$app->add(new Mmanos\Installer\Console\FrontendCommand);
$app->add(new Mmanos\Installer\Console\AuthorizeCommand);

$app->run();
